language: node_js
sudo: false
os:
  - linux
  - osx
  - windows
node_js:
  - "node"
  - "lts/*"
cache:
  directories:
    - node_modules
  before_script:
  - npm install
  script:
  - npm test
git:
  autocrlf: input